### ISSUE TITLE
typecheck-plugin-nat-simple-0.1.0.11 fails to build with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [YoshikuniJujo/typecheck-plugin-nat-simple#3]
Stackage Nightly say:

```
       /home/curators/work/unpack-dir/unpacked/typecheck-plugin-nat-simple-0.1.0.11-91084aa742cd2b463b1eed50dd6891310ea0ea19b8c0ba578b9cf5d7c96d3b8b/src/Plugin/Type14:19:57 [412/885210]
CheckWith.hs:49:35: error: [GHC-83865]        
           • Couldn't match expected type ‘Role’                                            
                         with actual type ‘GHC.Core.TyCo.Rep.Type’                          
           • In the first argument of ‘et’, namely ‘l’                                      
             In the expression: et l r                                                      
             In the first argument of ‘pure’, namely ‘(et l r, w)’                          
          |                                   
       49 |         bool (throw em) (pure (et l r, w)) =<< ck gs ds w                                                                                                                    
          |                                   ^                                             
                                              
       /home/curators/work/unpack-dir/unpacked/typecheck-plugin-nat-simple-0.1.0.11-91084aa742cd2b463b1eed50dd6891310ea0ea19b8c0ba578b9cf5d7c96d3b8b/src/Plugin/TypeCheck/Nat/Simple/Type
CheckWith.hs:52:40: error: [GHC-83865]        
           • Couldn't match type ‘GHC.Core.TyCo.Rep.Type                                    
                                  -> GHC.Core.TyCo.Rep.Coercion’                            
                            with ‘GHC.Core.TyCo.Rep.Coercion’                               
             Expected: Role                   
                       -> GHC.Core.TyCo.Rep.Type -> GHC.Core.TyCo.Rep.Coercion                                                                                                           
               Actual: Role                   
                       -> GHC.Core.TyCo.Rep.Type                                            
                       -> GHC.Core.TyCo.Rep.Type                                            
                       -> GHC.Core.TyCo.Rep.Coercion                                        
           • Probable cause: ‘mkUnivCo’ is applied to too few arguments                                                                                                                  
             In the second argument of ‘(.)’, namely                                        
               ‘mkUnivCo (PluginProv hd) Nominal’                                           
             In the expression:               
               ((EvExpr . Coercion) .) . mkUnivCo (PluginProv hd) Nominal                                                                                                                
             In an equation for ‘et’:                                                       
                 et = ((EvExpr . Coercion) .) . mkUnivCo (PluginProv hd) Nominal                                                                                                         
          |                                   
       52 |         et = ((EvExpr . Coercion) .) . mkUnivCo (PluginProv hd) Nominal                                                                                                      
          |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                      
                                              
       /home/curators/work/unpack-dir/unpacked/typecheck-plugin-nat-simple-0.1.0.11-91084aa742cd2b463b1eed50dd6891310ea0ea19b8c0ba578b9cf5d7c96d3b8b/src/Plugin/TypeCheck/Nat/Simple/Type
CheckWith.hs:52:65: error: [GHC-83865]        
           • Couldn't match expected type ‘[GHC.Core.TyCo.Rep.Coercion]’                                                                                                                 
                         with actual type ‘Role’                                            
           • In the second argument of ‘mkUnivCo’, namely ‘Nominal’                                                                                                                      
             In the second argument of ‘(.)’, namely                                        
               ‘mkUnivCo (PluginProv hd) Nominal’                                           
             In the expression:               
               ((EvExpr . Coercion) .) . mkUnivCo (PluginProv hd) Nominal                                                                                                                
          |                                   
       52 |         et = ((EvExpr . Coercion) .) . mkUnivCo (PluginProv hd) Nominal                                                                                                      
          |                                                                 ^^^^^^^   
```
