### ISSUE TITLE
Module ‘GHC.Tc.Types’ does not export ‘TcPluginSolveResult(..)’

### ISSUE THREAD

**Issue by juhp** [YoshikuniJujo/typecheck-plugin-nat-simple#1]
0.1.0.9 fails to build with Stackage LTS 20 (ghc-9.2.5)
```
Building library for typecheck-plugin-nat-simple-0.1.0.9..
[13 of 14] Compiling Plugin.TypeCheck.Nat.Simple.TypeCheckWith

/var/stackage/work/unpack-dir/unpacked/typecheck-plugin-nat-simple-0.1.0.9-df55f5f4e70c629f845ad81fdbc66c1a4beee5af07cb8d8cb5c4958324eb40d0/src/Plugin/TypeCheck/Nat/Simple/TypeCheckWith.hs:12:36: error:
    Module ‘GHC.Tc.Types’ does not export ‘TcPluginSolveResult(..)’
   |
12 | import GHC.Tc.Types (TcPlugin(..), TcPluginSolveResult(..))
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by juhp** [comment]
Not sure if you need a bound, or CI for different ghc major versions? :)
